//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAutomation.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorSwitchSensor
    {
        public int Id { get; set; }
        public int SensorReadingID { get; set; }
        public bool Open { get; set; }
    
        public virtual SensorReading SensorReading { get; set; }
    }
}
